'use client'

import OrgSidebar from '../../components/OrgSidebar'
import OrgTopbar from '../../components/OrgTopbar'
import { useCatalogue } from '../../context/CatalogueContext'

export default function OrganizationApplicationsPage() {
  const { addAudit, applications, currentOrg, orgLoginId, registerApplication, registerAppForm, registerAppModal, setAppCredentialModal, setApplications, setOrgApprovalModal, setRegisterAppForm, setRegisterAppModal, setView } = useCatalogue()
  const orgId = currentOrg?.id || orgLoginId
  const orgApps = applications.filter((app) => app.orgId === orgId)
  return (
    <div className="org-dashboard-shell">
      <OrgSidebar activeItem="Applications" />
      <main className="org-main org-applications-main">
        <OrgTopbar heading={`Applications - ${currentOrg?.name || orgId}`} subtitle="Manage applications registered by your organization." action={<button type="button" className="primary-button" onClick={() => setRegisterAppModal(true)}>Register Application</button>} />
        <div className="panel-copy"><p>Manage your applications and submit new applications to the platform for approval.</p></div>
        <section style={{padding:12}}>{orgApps.length === 0 ? <div className="form-card"><p>No applications yet. Click Register Application to add one.</p></div> : <div className="org-app-grid">{orgApps.map((app) => <div key={app.id} className="org-app-card"><div className="org-app-left"><div className="app-icon">{(app.type || 'app').charAt(0).toUpperCase()}</div><div className="app-info"><div className="approval-name">{app.name}</div><div className="approval-meta">{app.type} - {app.id}</div><div className="app-desc"><small>{app.description}</small></div><div className="app-meta-row"><span className={`app-status-badge status-${app.status}`}>{app.status}</span><span className="created-at">{app.createdAt}</span></div></div></div><div className="org-app-actions"><button className="ghost-button" onClick={() => setOrgApprovalModal({ type: 'app', item: app })}>View</button>{app.status === 'pending' && <button className="secondary-button" onClick={() => { setApplications((prev) => prev.filter((item) => item.id !== app.id)); addAudit('Withdraw Application', `Withdrew ${app.name}`) }}>Withdraw</button>}{app.status === 'approved' && <><button className="secondary-button" onClick={() => { navigator.clipboard?.writeText(app.clientId || ''); alert('Client ID copied to clipboard') }}>Copy Client ID</button><button className="secondary-button" onClick={() => setAppCredentialModal({ app, clientId: app.clientId, clientSecret: app.clientSecret })}>View Credentials</button></>}</div></div>)}</div>}</section>
      </main>
      {registerAppModal && <div className="modal-backdrop" onClick={() => setRegisterAppModal(false)}><div className="modal-card register-modal" onClick={(e) => e.stopPropagation()}><div className="modal-header"><h3>Register Application</h3><button className="close-button" onClick={() => setRegisterAppModal(false)}>x</button></div><div className="form-card"><div className="register-form-grid"><label className="full">Application Name<input value={registerAppForm.name} onChange={(e) => setRegisterAppForm((prev) => ({ ...prev, name: e.target.value }))} placeholder="Identity Suite" /></label><label>Type<select value={registerAppForm.type} onChange={(e) => setRegisterAppForm((prev) => ({ ...prev, type: e.target.value }))}><option value="web">Web</option><option value="mobile">Mobile</option><option value="spa">Single Page App</option><option value="backend">Backend</option></select></label><label>Contact Email<input value={registerAppForm.contactEmail} onChange={(e) => setRegisterAppForm((prev) => ({ ...prev, contactEmail: e.target.value }))} placeholder="owner@company.com" /></label><label>Domain<input value={registerAppForm.domain} onChange={(e) => setRegisterAppForm((prev) => ({ ...prev, domain: e.target.value }))} placeholder="app.company.com" /></label><label className="full">Description<textarea value={registerAppForm.description} onChange={(e) => setRegisterAppForm((prev) => ({ ...prev, description: e.target.value }))} placeholder="Describe what this application does" /></label><label>Redirect URI*<input value={registerAppForm.redirectUri} onChange={(e) => setRegisterAppForm((prev) => ({ ...prev, redirectUri: e.target.value }))} placeholder="https://app.company.com/callback" /></label><label>Logout URI<input value={registerAppForm.logoutUri} onChange={(e) => setRegisterAppForm((prev) => ({ ...prev, logoutUri: e.target.value }))} placeholder="https://app.company.com/logout" /></label></div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:12}}><button className="secondary-button" onClick={() => setRegisterAppModal(false)}>Cancel</button><button className="primary-button" onClick={async () => { try { await registerApplication(); alert('Application submitted for platform approval') } catch (error) { alert(error instanceof Error ? error.message : 'Application registration failed') } }}>Submit</button></div></div></div></div>}
    </div>
  )
}
